#!/usr/bin/env python3
"""Build Cursor and Copilot rule files from .ai/rules/ source of truth.

Also updates the managed import blocks in CLAUDE.md and AGENTS.md.
Idempotent: safe to run multiple times.
Writes to: .cursor/rules/  .github/instructions/  CLAUDE.md  AGENTS.md
"""

import sys
from pathlib import Path

try:
    import tomllib  # Python 3.11+
except ImportError:
    tomllib = None

SCRIPT_PATH = Path(__file__).resolve()
REPO_ROOT = SCRIPT_PATH.parents[4]
RULES_SRC = REPO_ROOT / ".ai" / "rules"

CURSOR_OUT = REPO_ROOT / ".cursor" / "rules"
COPILOT_OUT = REPO_ROOT / ".github" / "instructions"
CLAUDE_MD = REPO_ROOT / "CLAUDE.md"
AGENTS_MD = REPO_ROOT / "AGENTS.md"

IMPORTS_START = "<!-- cross-rules:imports:start -->"
IMPORTS_END = "<!-- cross-rules:imports:end -->"
GENERATED_COMMENT = "<!-- generated by build-rules script — edit .ai/rules/{name}.md to update -->"

rules_processed = 0
files_written = 0
files_skipped = 0
warnings = 0
errors = 0


def _parse_yaml_simple(text: str) -> dict:
    """Minimal YAML parser for the sidecar format (no third-party deps).

    Supports one level of nesting only: top-level keys whose values are either
    a scalar or an indented block of scalar key: value pairs.
    """
    result: dict = {}
    current_key = None
    for line in text.splitlines():
        if not line.strip() or line.strip().startswith("#"):
            continue
        if line[0] != " " and line[0] != "\t":
            if ":" in line:
                k, _, v = line.partition(":")
                k = k.strip()
                v = v.strip().strip('"').strip("'")
                if v:
                    result[k] = v
                else:
                    result[k] = {}
                    current_key = k
            continue
        if current_key is not None and ":" in line:
            k, _, v = line.strip().partition(":")
            k = k.strip()
            v = v.strip().strip('"').strip("'")
            if isinstance(result.get(current_key), dict):
                result[current_key][k] = v
    return result


def parse_sidecar(path: Path) -> dict | None:
    global errors
    try:
        return _parse_yaml_simple(path.read_text(encoding="utf-8"))
    except Exception as e:
        print(f"ERROR: could not parse {path}: {e}", file=sys.stderr)
        errors += 1
        return None


def write_if_changed(path: Path, content: str) -> None:
    global files_written, files_skipped
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and path.read_text(encoding="utf-8") == content:
        files_skipped += 1
        return
    path.write_text(content, encoding="utf-8")
    files_written += 1


def build_cursor_content(name: str, sidecar: dict | None, body: str) -> str:
    cursor = (sidecar or {}).get("cursor", {})
    description = cursor.get("description", "") if isinstance(cursor, dict) else ""
    globs = cursor.get("globs", "") if isinstance(cursor, dict) else ""
    always_apply = cursor.get("alwaysApply", "") if isinstance(cursor, dict) else ""

    fm_lines = ["---"]
    if description:
        fm_lines.append(f"description: {description}")
    if globs:
        fm_lines.append(f"globs: {globs}")
    if always_apply and str(always_apply).lower() == "true":
        fm_lines.append("alwaysApply: true")
    elif not globs:
        fm_lines.append("alwaysApply: true")
    else:
        fm_lines.append("alwaysApply: false")
    fm_lines.append("---")

    comment = GENERATED_COMMENT.format(name=name)
    return "\n".join(fm_lines) + "\n" + comment + "\n" + body


def build_copilot_content(name: str, sidecar: dict | None, body: str) -> str:
    copilot = (sidecar or {}).get("copilot", {})
    apply_to = copilot.get("applyTo", "") if isinstance(copilot, dict) else ""

    comment = GENERATED_COMMENT.format(name=name)
    if apply_to:
        return f"---\napplyTo: \"{apply_to}\"\n---\n{comment}\n{body}"
    return comment + "\n" + body


def update_imports_block(md_path: Path, rule_names: list[str]) -> None:
    global files_written, files_skipped, warnings

    import_lines = "\n".join(f"@file .ai/rules/{n}.md" for n in sorted(rule_names))
    new_block = f"{IMPORTS_START}\n{import_lines}\n{IMPORTS_END}"

    if not md_path.exists():
        warnings += 1
        print(f"WARNING: {md_path} does not exist — skipping import block update", file=sys.stderr)
        return

    text = md_path.read_text(encoding="utf-8")
    start_idx = text.find(IMPORTS_START)
    end_idx = text.find(IMPORTS_END)

    if start_idx != -1 and end_idx != -1 and end_idx > start_idx:
        new_text = text[:start_idx] + new_block + text[end_idx + len(IMPORTS_END):]
    else:
        warnings += 1
        print(
            f"WARNING: {md_path} has no managed imports block — appending it",
            file=sys.stderr,
        )
        new_text = text.rstrip("\n") + "\n\n" + new_block + "\n"

    if new_text == text:
        files_skipped += 1
        return
    md_path.write_text(new_text, encoding="utf-8")
    files_written += 1


def main() -> int:
    global rules_processed, errors, warnings

    if not RULES_SRC.is_dir():
        print(
            f"ERROR: {RULES_SRC} does not exist. "
            "Run 'init cross-rules' to scaffold the rules structure.",
            file=sys.stderr,
        )
        return 1

    md_files = sorted(RULES_SRC.glob("*.md"))
    yml_files = {p.stem for p in RULES_SRC.glob("*.yml")}

    # Warn about orphaned sidecars
    md_stems = {p.stem for p in md_files}
    for orphan in sorted(yml_files - md_stems):
        print(
            f"WARNING: .ai/rules/{orphan}.yml has no matching .md file — orphaned sidecar",
            file=sys.stderr,
        )
        warnings += 1

    rule_names: list[str] = []

    for md_path in md_files:
        name = md_path.stem
        body = md_path.read_text(encoding="utf-8")

        sidecar: dict | None = None
        yml_path = RULES_SRC / f"{name}.yml"
        if yml_path.is_file():
            sidecar = parse_sidecar(yml_path)
            if sidecar is None:
                continue  # parse error already recorded
        else:
            warnings += 1
            print(
                f"WARNING: .ai/rules/{name}.yml missing — treating rule as always-on",
                file=sys.stderr,
            )

        write_if_changed(CURSOR_OUT / f"{name}.mdc", build_cursor_content(name, sidecar, body))
        write_if_changed(COPILOT_OUT / f"{name}.md", build_copilot_content(name, sidecar, body))

        rule_names.append(name)
        rules_processed += 1

    update_imports_block(CLAUDE_MD, rule_names)
    update_imports_block(AGENTS_MD, rule_names)

    print()
    print("build-rules complete")
    print(f"  Rules processed : {rules_processed}")
    print(f"  Files written   : {files_written}")
    print(f"  Files skipped   : {files_skipped} (unchanged)")
    if warnings:
        print(f"  Warnings        : {warnings} (see above)")
    if errors:
        print(f"  Errors          : {errors} (see above)")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
